[build]
  command = "npm ci && npm run build"
  publish = "dist"

# Serve real asset files as-is (no SPA rewrite)
[[redirects]]
  from = "/assets/*"
  to = "/assets/:splat"
  status = 200

# Single Page App fallback for everything else
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
